AWSTemplateFormatVersion: 2010-09-09
Description: Parent stack to delpoy whole uat environment

Parameters:
  AWSTeam:
    Type: String
    Default: tpdt
  AWSEnv:
    Type: String
    MinLength: '3'
    MaxLength: '6'
    Default: uat
    AllowedPattern: ^dev|prod|uat$
    ConstraintDescription: must be dev, prod, uat
  GlueIamRole:
    Type: String
    Default: arn:aws:iam::581813634934:role/tpdt-etl-glue-globalstack
  GlueVersion:
    Type: String
    Default: 3.0
  GluejobNumberOfWorkers:
    Type: Number
    Description: number of workers for Glue Job
    Default: 2
  GlueSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0c1285c4bb53310da
  SecretManagerNameDB01:
    Type: String
    Default: tpdt-db01-uat
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-03633e8a484a500e3
  lambdaIamRole:
    Type: String
    Default: arn:aws:iam::581813634934:role/tpdt-lambda-uat
  lambdaFunctionFolder:
    Type: String
    Default: Lambda/Functions
  accountid:
    Type: String
    Default: '581813634934'


Resources:
  Architecture:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts-${AWSEnv}.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-architecture-stack.yml'
      Parameters:
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueSecurityGroupID: !Ref GlueSecurityGroupID
        SecretManagerNameDB01: !Ref SecretManagerNameDB01
        SubnetID: !Ref SubnetID


  Staging:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts-${AWSEnv}.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-staging-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts-${AWSEnv}'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary

  Customers:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts-${AWSEnv}.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-customers-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts-${AWSEnv}'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary
        CrawlerS3staging: !GetAtt Architecture.Outputs.CrawlerS3staging

  Transactions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts-${AWSEnv}.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-transactions-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts-${AWSEnv}'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary
        CrawlerS3dw: !GetAtt Architecture.Outputs.CrawlerS3dw

  lms:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts-${AWSEnv}.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-lms-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts-${AWSEnv}'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary


  stampmission:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts-${AWSEnv}.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-stampmission-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts-${AWSEnv}'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary

  segmentation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-segmentation-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary

  adobe:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-adobe-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary

  ga:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts-${AWSEnv}.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-ga-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts-${AWSEnv}'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary
        lambdaIamRole: !Ref lambdaIamRole
        accountid: !Ref accountid