AWSTemplateFormatVersion: 2010-09-09
Description: Parent stack to delpoy whole prod environment

Parameters:
  AWSTeam:
    Type: String
    Default: tpdt
  AWSEnv:
    Type: String
    MinLength: '3'
    MaxLength: '6'
    Default: prod
    AllowedPattern: ^dev|prod|uat$
    ConstraintDescription: must be dev, prod, uat
  GlueIamRole:
    Type: String
    Default: arn:aws:iam::244353132907:role/analytic-etl-glue-globalstack
  GlueVersion:
    Type: String
    Default: 4.0
  GluejobNumberOfWorkers:
    Type: Number
    Description: number of workers for Glue Job
    Default: 2
  GlueSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-09008dc3534447e51
  SecretManagerNameDB01:
    Type: String
    Default: tpdt_db01
  SecretManagerNameDB02:
    Type: String
    Default: tpdt_db02
  SecretManagerNameFoodOrdering:
    Type: String
    Default: tpdt_foodordering
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0406aa5bbf9d46605
  lambdaIamRole:
    Type: String
    Default: arn:aws:iam::244353132907:role/tpdt-lambda
  accountid:
    Type: String
    Default: '244353132907'
  SecretManagerNameRedshiftMaster:
    Type: String
    Default: tpdt_03redshift_master
  RedShiftSnapshotRetentionPeriod:
    Type: Number
    Default: 30
  RedShiftClusterType:
    Type: String
    Description: The type of cluster
    AllowedPattern: ^multi-node|single-node$
    Default: multi-node
  RedShiftNodeType:
    Type: String
    Description: The node type to be provisioned for the cluster
    Default: dc2.large
  RedShiftNumberOfNodes:
    Type: String
    Description: The number of compute nodes in the cluster
    Default: 2
  RedShiftPreferredMaintenanceWindow:
    Type: String
    Description: The weekly time range (in UTC) during which automated cluster maintenance can occur in format of ddd:hh24:mi-ddd:hh24:mi
    Default: Sat:03:00-Sat:03:30
  RedShiftVPCSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0082035678856eba5
  PrivateSubnet1ID:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0768b1e8f3bd1a45b
  PrivateSubnet2ID:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0406aa5bbf9d46605
  PrivateSubnet3ID:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-064c7a365dab908f5


Conditions:
  IsNotPrd: !Not
    - !Equals
      - !Ref AWSEnv
      - 'prod'

Resources:
# Nested Stacks - Start
  Architecture:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-architecture-stack.yml'
      Parameters:
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueSecurityGroupID: !Ref GlueSecurityGroupID
        SecretManagerNameDB01: !Ref SecretManagerNameDB01
        SubnetID: !Ref SubnetID
        SecretManagerNameRedshiftMaster: !Ref SecretManagerNameRedshiftMaster
        RedShiftSnapshotRetentionPeriod: !Ref RedShiftSnapshotRetentionPeriod
        RedShiftClusterType: !Ref RedShiftClusterType
        RedShiftNodeType: !Ref RedShiftNodeType
        RedShiftNumberOfNodes: !Ref RedShiftNumberOfNodes
        RedShiftPreferredMaintenanceWindow: !Ref RedShiftPreferredMaintenanceWindow
        RedShiftVPCSecurityGroupID: !Ref RedShiftVPCSecurityGroupID
        PrivateSubnet1ID: !Ref PrivateSubnet1ID
        PrivateSubnet2ID: !Ref PrivateSubnet2ID
        PrivateSubnet3ID: !Ref PrivateSubnet3ID

  Staging:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-staging-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary

  Customers:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-customers-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary
        CrawlerS3staging: !GetAtt Architecture.Outputs.CrawlerS3staging
        lambdaIamRole: !Ref lambdaIamRole
        accountid: !Ref accountid

  Transactions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-transactions-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary
        CrawlerS3dw: !GetAtt Architecture.Outputs.CrawlerS3dw
        CrawlerS3staging: !GetAtt Architecture.Outputs.CrawlerS3staging
        S3AthenaResult: !GetAtt Architecture.Outputs.S3AthenaResult
        lambdaIamRole: !Ref lambdaIamRole
        accountid: !Ref accountid

  lms:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-lms-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary

  parking:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-parking-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary
        lambdaIamRole: !Ref lambdaIamRole
        accountid: !Ref accountid

  stampmission:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-stampmission-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary

  foodordering:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-foodorder-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary

  segmentation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-segmentation-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary

  cdp:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-cdp-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary
        lambdaIamRole: !Ref lambdaIamRole

  adobe:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-adobe-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary

  campaign:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-campaign-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary

  prodCustomResource:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-prod-custom-resources-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueSecurityGroupID: !Ref GlueSecurityGroupID
        SecretManagerNameDB02: !Ref SecretManagerNameDB02
        SubnetID: !Ref SubnetID
        SecretManagerNameFoodOrdering: !Ref SecretManagerNameFoodOrdering
        GlueDB01replica: !GetAtt Architecture.Outputs.GlueDB01replica
        GlueConnector01replica: !GetAtt Architecture.Outputs.GlueConnector01replica
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        GlueDBMagicCart: !GetAtt foodordering.Outputs.GlueDBMagicCart

  automation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-automation-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        lambdaIamRole: !Ref lambdaIamRole
        accountid: !Ref accountid

  ga:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWSTeam}-artifacts.s3.ap-east-1.amazonaws.com/Stacks/${AWSTeam}-ga-stack.yml'
      Parameters:
        AWSTeam: !Ref AWSTeam
        AWSEnv: !Ref AWSEnv
        GlueIamRole: !Ref GlueIamRole
        GlueVersion: !Ref GlueVersion
        GlueDBdw: !GetAtt Architecture.Outputs.GlueDBdw
        GlueConnector03redshift: !GetAtt Architecture.Outputs.GlueConnector03redshift
        S3ArtifactBucket: !Sub '${AWSTeam}-artifacts'
        GluejobNumberOfWorkers: !Ref GluejobNumberOfWorkers
        S3NameGlueTemporary: !GetAtt Architecture.Outputs.S3NameGlueTemporary
        lambdaIamRole: !Ref lambdaIamRole
        accountid: !Ref accountid

# Nested Stacks - End