AWSTemplateFormatVersion: 2010-09-09
Description: Stack to deploy resources and tasks for member, mall, partner and shop


Parameters:
  AWSTeam:
    Type: String
    Default: tpdt
  AWSEnv:
    Type: String
    MinLength: '3'
    MaxLength: '6'
    AllowedPattern: ^dev|prod|uat$
    ConstraintDescription: must be dev, prod, uat
  DBprefix:
    Type: String
    Default: tp03
  GlueIamRole:
    Type: String
  GlueVersion:
    Type: String
  GlueDBdw:
    Type: String
  GlueDB01replica:
    Type: String
  S3ArtifactBucket:
    Type: String
  GluejobNumberOfWorkers:
    Type: Number
    Description: number of workers for Glue Job
  S3NameGlueTemporary:
    Type: String
  GlueConnector01replica:
    Type: String



Conditions:
  IsNotPrd: !Not
    - !Equals
      - !Ref AWSEnv
      - 'prod'

Resources:
# Creating S3 Buckets - Start
  S3segmentation:
    Description: bucket to store segmentation ETL result
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Join
        - '-'
        - - !Ref AWSTeam
          - segmentation
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: application
          Value: !Ref AWSTeam
        - Key: environment
          Value: !Ref AWSEnv
        - Key: stack
          Value: segmentation
# Creating S3 Buckets - End

# Creating Glue DataBase - Start
  GlueDBsegmentation:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: Database to connect S3segmentation bucket
        LocationUri: !Sub 's3://${S3segmentation}/'
        Name: !Join
          - '_'
          - - !Ref AWSTeam
            - 03segmentation
            - !If
              - IsNotPrd
              - !Ref AWSEnv
              - !Ref 'AWS::NoValue'
# Creating Glue DataBase - End

# Creating Glue S3 Crawler - Start
  CrawlerS3segmentation:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - s3
          - segmentation
          - crawler
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Role: !Ref GlueIamRole
      Description: Crawl segmentation data in S3
      DatabaseName: !Ref GlueDBsegmentation
      Targets:
        S3Targets:
          - Path: !Sub 's3://${S3segmentation}'
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Tags: {
        application: !Ref AWSTeam ,
        environment: !Ref AWSEnv ,
        stack: segmentation
        }
# Creating Glue S3 Crawler - End

# PB related jobs - Start
  dwProfessionalBuyer:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: !Join
          - ''
          - - "s3://"
            - !Ref S3ArtifactBucket
            - '/Glue/Scripts/'
            - !Ref AWSTeam
            - "_dw_professional_buyer"
      Connections:
        Connections:
          - !Ref GlueConnector01replica
      DefaultArguments:
        --env: !Ref AWSEnv
        --TempDir: !Sub 's3://${S3NameGlueTemporary}/'
        --job-bookmark-option: job-bookmark-disable
        --job-language: python
        --enable-metrics: ''
      ExecutionProperty:
        MaxConcurrentRuns: 1
      GlueVersion: !Ref GlueVersion
      MaxRetries: 0
      Name: !Sub '${AWSTeam}_dw_professional_buyer'
      NumberOfWorkers: !Ref GluejobNumberOfWorkers
      Role: !Ref GlueIamRole
      Timeout: 2880
      WorkerType: G.1X
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: segmentation
        BusinessFunction: professionalbuyer

# PB related jobs - End

# Member Profile related jobs - Start
  MemberProfile:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: !Join
          - ''
          - - "s3://"
            - !Ref S3ArtifactBucket
            - '/Glue/Scripts/'
            - !Ref AWSTeam
            - "_member_profile"
      DefaultArguments:
        --env: !Ref AWSEnv
        --TempDir: !Sub 's3://${S3NameGlueTemporary}/'
        --job-bookmark-option: job-bookmark-disable
        --job-language: python
        --enable-metrics: ''
      ExecutionProperty:
        MaxConcurrentRuns: 1
      GlueVersion: !Ref GlueVersion
      MaxRetries: 0
      Name: !Sub '${AWSTeam}_member_profile'
      NumberOfWorkers: !Ref GluejobNumberOfWorkers
      Role: !Ref GlueIamRole
      Timeout: 2880
      WorkerType: G.1X
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: segmentation
        BusinessFunction: segmentation
# Member Profile related jobs - End


# Creating Glue Workflow - Start
  # PB Related Workflow - Start
  SegmentationGlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - segmentation
          - turncate
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: segmentation
        BusinessFunction: segmentation
  # PB Related Workflow - End

  # Member Profile Related Workflow - Start
  MemberProfileGlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - segmentation
          - member
          - profile
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: segmentation
        BusinessFunction: segmentation
  # Member Profile Related Workflow - End

# Creating Glue Workflow - End


# Creating Glue Trigger - Start
  # PB Related Trigger - Start
  SegmentationGlueTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
        - JobName: !Ref dwProfessionalBuyer
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - segmentation
          - turncate
          - schedule
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Type: "SCHEDULED"
      Schedule: cron(5 12 20 * ? *)
      StartOnCreation: true
      WorkflowName: !Ref SegmentationGlueWorkflow
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: segmentation
        BusinessFunction: segmentation
  # PB Related Trigger - End

  # Member Profile Related Trigger - Start
  MemberProfileGlueTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
        - JobName: !Ref MemberProfile
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - segmentation
          - member
          - profile
          - schedule
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Type: "SCHEDULED"
      Schedule: cron(45 00 * * ? *)
      StartOnCreation: true
      WorkflowName: !Ref MemberProfileGlueWorkflow
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: segmentation
        BusinessFunction: segmentation

  s3SegmentationCrawlerTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
        - CrawlerName: !Ref CrawlerS3segmentation
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - segmentation
          - crawler
          - trigger
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Type: "CONDITIONAL"
      WorkflowName: !Ref MemberProfileGlueWorkflow
      StartOnCreation: true
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            JobName: !Ref MemberProfile
            State: SUCCEEDED
        Logical: AND
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: segmentation
        BusinessFunction: segmentation
  # Member Profile Related Trigger - End
# Creating Glue Trigger - End
