AWSTemplateFormatVersion: 2010-09-09
Description: Stack to deploy resources and tasks for e-stamp and mission


Parameters:
  AWSTeam:
    Type: String
    Default: tpdt
  AWSEnv:
    Type: String
    MinLength: '3'
    MaxLength: '6'
    AllowedPattern: ^dev|prod|uat$
    ConstraintDescription: must be dev, prod, uat
  DBprefix:
    Type: String
    Default: tp03
  GlueIamRole:
    Type: String
  GlueVersion:
    Type: String
  GlueDBdw:
    Type: String
  GlueDB01replica:
    Type: String
  S3ArtifactBucket:
    Type: String
  GluejobNumberOfWorkers:
    Type: Number
    Description: number of workers for Glue Job
  S3NameGlueTemporary:
    Type: String
  GlueConnector01replica:
    Type: String


Conditions:
  IsNotPrd: !Not
    - !Equals
      - !Ref AWSEnv
      - 'prod'

Resources:
# Creating S3 Buckets - Start
  S3stampmission:
    Description: bucket to store data related to stamp and mission
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Join
        - '-'
        - - !Ref AWSTeam
          - stampmission
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: application
          Value: !Ref AWSTeam
        - Key: environment
          Value: !Ref AWSEnv
        - Key: stack
          Value: stampmission
# Creating S3 Buckets - End

# Creating Glue DataBase - Start
  GlueDBstampmission:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: Database to connect S3stampmission bucket
        LocationUri: !Sub 's3://${S3stampmission}/'
        Name: !Join
          - '_'
          - - !Ref AWSTeam
            - 03stampmission
            - !If
              - IsNotPrd
              - !Ref AWSEnv
              - !Ref 'AWS::NoValue'
# Creating Glue DataBase - End

# Creating Glue S3 Crawler - Start
  CrawlerS3stampmission:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - s3
          - stampmission
          - crawler
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Role: !Ref GlueIamRole
      Description: Crawl stampmission data in S3
      DatabaseName: !Ref GlueDBstampmission
      Targets:
        S3Targets:
          - Path: !Sub 's3://${S3stampmission}'
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Tags: {
        application: !Ref AWSTeam ,
        environment: !Ref AWSEnv ,
        stack: stampmission
        }

  CrawlerS3stampmissionMiddle:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - s3
          - stampmission
          - Middle
          - crawler
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Role: !Ref GlueIamRole
      Description: Crawl stampmission data in S3
      DatabaseName: !Ref GlueDBstampmission
      Targets:
        S3Targets:
          - Path: !Sub 's3://${S3stampmission}'
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Tags: {
        application: !Ref AWSTeam ,
        environment: !Ref AWSEnv ,
        stack: stampmission
        }
# Creating Glue S3 Crawler - End

# Creating Glue Jobs - Start
  # Stamp related jobs - Start
  odsStamp:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: !Join
          - ''
          - - "s3://"
            - !Ref S3ArtifactBucket
            - '/Glue/Scripts/'
            - !Ref AWSTeam
            - "_ods_stamp"
      Connections:
        Connections:
          - !Ref GlueConnector01replica
      DefaultArguments:
        --env: !Ref AWSEnv
        --TempDir: !Sub 's3://${S3NameGlueTemporary}/'
        --job-bookmark-option: job-bookmark-disable
        --job-language: python
        --enable-metrics: ''
      ExecutionProperty:
        MaxConcurrentRuns: 1
      GlueVersion: !Ref GlueVersion
      MaxRetries: 0
      Name: !Sub '${AWSTeam}_ods_stamp'
      NumberOfWorkers: !Ref GluejobNumberOfWorkers
      Role: !Ref GlueIamRole
      Timeout: 2880
      WorkerType: G.1X
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: stampmission
        BusinessFunction: stamp

  dwStamp:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: !Join
          - ''
          - - "s3://"
            - !Ref S3ArtifactBucket
            - '/Glue/Scripts/'
            - !Ref AWSTeam
            - "_dw_stamp"
      Connections:
        Connections:
          - !Ref GlueConnector01replica
      DefaultArguments:
        --env: !Ref AWSEnv
        --TempDir: !Sub 's3://${S3NameGlueTemporary}/'
        --job-bookmark-option: job-bookmark-disable
        --job-language: python
        --enable-metrics: ''
      ExecutionProperty:
        MaxConcurrentRuns: 1
      GlueVersion: !Ref GlueVersion
      MaxRetries: 0
      Name: !Sub '${AWSTeam}_dw_stamp'
      NumberOfWorkers: 6
      Role: !Ref GlueIamRole
      Timeout: 2880
      WorkerType: G.1X
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: stampmission
        BusinessFunction: stamp
  # Stamp related jobs - End

  # Mission related jobs - Start
  odsMissions:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: !Join
          - ''
          - - "s3://"
            - !Ref S3ArtifactBucket
            - '/Glue/Scripts/'
            - !Ref AWSTeam
            - "_ods_missions"
      Connections:
        Connections:
          - !Ref GlueConnector01replica
      DefaultArguments:
        --env: !Ref AWSEnv
        --TempDir: !Sub 's3://${S3NameGlueTemporary}/'
        --job-bookmark-option: job-bookmark-disable
        --job-language: python
        --enable-metrics: ''
      ExecutionProperty:
        MaxConcurrentRuns: 1
      GlueVersion: !Ref GlueVersion
      MaxRetries: 0
      Name: !Sub '${AWSTeam}_ods_missions'
      NumberOfWorkers: 4
      Role: !Ref GlueIamRole
      Timeout: 2880
      WorkerType: G.1X
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: stampmission
        BusinessFunction: mission
  # Mission related jobs - End
# Creating Glue Jobs - Start

# Creating Glue Workflow - Start
  # Stamp Mission Related Workflow - Start
  StampMissionGlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - stampmission
          - turncate
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: stampmission
        BusinessFunction: stampmission
  # Stamp Mission Related Workflow - End
# Creating Glue Workflow - End

# Creating Glue Trigger - Start
  # Stamp Mission Related Trigger - Start
  StampGlueTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
        - JobName: !Ref odsStamp
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - stamp
          - turncate
          - schedule
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Type: "SCHEDULED"
      Schedule: cron(45 19 * * ? *)
      StartOnCreation: true
      WorkflowName: !Ref StampMissionGlueWorkflow
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: stampmission
        BusinessFunction: stamp

  MissionGlueTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
        - JobName: !Ref odsMissions
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - odsMissions
          - trigger
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Type: "CONDITIONAL"
      WorkflowName: !Ref StampMissionGlueWorkflow
      StartOnCreation: true
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            JobName: !Ref odsStamp
            State: SUCCEEDED
        Logical: AND
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: stampmission
        BusinessFunction: mission

  stampCrawlerMiddleGlueTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
        - CrawlerName: !Ref CrawlerS3stampmissionMiddle
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - stamp
          - middle
          - crawler
          - trigger
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Type: "CONDITIONAL"
      WorkflowName: !Ref StampMissionGlueWorkflow
      StartOnCreation: true
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            JobName: !Ref odsMissions
            State: SUCCEEDED
        Logical: AND
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: stampmission
        BusinessFunction: stamp

  dwStampGlueTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
        - JobName: !Ref dwStamp
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - dwStamp
          - trigger
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Type: "CONDITIONAL"
      WorkflowName: !Ref StampMissionGlueWorkflow
      StartOnCreation: true
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            CrawlerName: !Ref CrawlerS3stampmissionMiddle
            CrawlState: SUCCEEDED
        Logical: AND
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: stampmission
        BusinessFunction: stamp

  stampCrawlerGlueTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
        - CrawlerName: !Ref CrawlerS3stampmission
      Name: !Join
        - '-'
        - - !Ref AWSTeam
          - stamp
          - crawler
          - trigger
          - !If
            - IsNotPrd
            - !Ref AWSEnv
            - !Ref 'AWS::NoValue'
      Type: "CONDITIONAL"
      WorkflowName: !Ref StampMissionGlueWorkflow
      StartOnCreation: true
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            JobName: !Ref dwStamp
            State: SUCCEEDED
        Logical: AND
      Tags:
        application: !Ref AWSTeam
        environment: !Ref AWSEnv
        stack: stampmission
        BusinessFunction: stamp
  # Stamp Mission Related Trigger - End
# Creating Glue Trigger- End
